<?php

namespace Modules\Admin\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Modules\Admin\Entities\ArabicLetter;

class ArabicLetterSeeder extends Seeder
{
    public function run(): void
    {
        $letters = [
            // Al-Jawf Letters
            [
                'letter_arabic' => 'ا',
                'letter_name_arabic' => 'ألف',
                'letter_name_urdu' => 'الف',
                'letter_name_english' => 'Alif',
                'makhraj_category' => 'Al-Jawf',
                'makhraj_description_urdu' => 'حلق اور منہ کی خالی جگہ سے ادا کیا جاتا ہے',
                'makhraj_description_english' => 'Pronounced from the empty space in the mouth and throat',
                'pronunciation_tips_urdu' => 'منہ کھول کر آہستہ سے ادا کریں',
                'pronunciation_tips_english' => 'Open your mouth and pronounce gently',
                'shape_isolated' => 'ا',
                'shape_initial' => 'ا',
                'shape_middle' => 'ـا',
                'shape_final' => 'ـا',
                'display_order' => 1,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => true,
                'similar_urdu_sounds' => json_encode(['الف']),
                'common_mistakes_urdu' => json_encode(['الف کو ہلکا پڑھنا', 'الف کو غنہ کے ساتھ پڑھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing Alif lightly', 'Adding ghunnah to Alif']),
            ],
            [
                'letter_arabic' => 'ب',
                'letter_name_arabic' => 'باء',
                'letter_name_urdu' => 'بے',
                'letter_name_english' => 'Ba',
                'makhraj_category' => 'Ash-Shafataan',
                'makhraj_description_urdu' => 'ہونٹوں کو ملا کر ادا کیا جاتا ہے',
                'makhraj_description_english' => 'Pronounced by pressing the lips together',
                'pronunciation_tips_urdu' => 'ہونٹوں کو مضبوطی سے ملا کر آواز نکالیں',
                'pronunciation_tips_english' => 'Press your lips firmly together and release with sound',
                'shape_isolated' => 'ب',
                'shape_initial' => 'بـ',
                'shape_middle' => 'ـبـ',
                'shape_final' => 'ـب',
                'display_order' => 2,
                'has_ghunnah' => false,
                'is_qalqalah' => true,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['بے']),
                'common_mistakes_urdu' => json_encode(['ہونٹوں کو کھلا رکھنا', 'انگریزی B کی طرح پڑھنا']),
                'common_mistakes_english' => json_encode(['Keeping lips open', 'Pronouncing like English B']),
            ],
            [
                'letter_arabic' => 'ت',
                'letter_name_arabic' => 'تاء',
                'letter_name_urdu' => 'تے',
                'letter_name_english' => 'Ta',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'دانتوں کی جڑ اور زبان کی نوک سے',
                'makhraj_description_english' => 'From the tip of the tongue and the gum line of the upper front teeth',
                'pronunciation_tips_urdu' => 'زبان کی نوک کو اوپر کے دانتوں کی جڑ سے لگائیں',
                'pronunciation_tips_english' => 'Place the tip of your tongue against the gum line of your upper front teeth',
                'shape_isolated' => 'ت',
                'shape_initial' => 'تـ',
                'shape_middle' => 'ـتـ',
                'shape_final' => 'ـت',
                'display_order' => 3,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['تے']),
                'common_mistakes_urdu' => json_encode(['انگریزی T کی طرح پڑھنا', 'دانتوں کے درمیان زبان رکھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like English T', 'Placing tongue between teeth']),
            ],
            [
                'letter_arabic' => 'ث',
                'letter_name_arabic' => 'ثاء',
                'letter_name_urdu' => 'ثے',
                'letter_name_english' => 'Tha',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'زبان کی نوک اور اوپر کے دانتوں کے کنارے سے',
                'makhraj_description_english' => 'From the tip of the tongue and the edges of the upper front teeth',
                'pronunciation_tips_urdu' => 'زبان کی نوک اوپر کے دانتوں کے درمیان رکھ کر ہوا نکالیں',
                'pronunciation_tips_english' => 'Place the tip of your tongue between your upper front teeth and blow air',
                'shape_isolated' => 'ث',
                'shape_initial' => 'ثـ',
                'shape_middle' => 'ـثـ',
                'shape_final' => 'ـث',
                'display_order' => 4,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['ثے']),
                'common_mistakes_urdu' => json_encode(['سے یا زے پڑھنا', 'دانتوں کے درمیان زبان نہ رکھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like Sa or Za', 'Not placing tongue between teeth']),
            ],
            [
                'letter_arabic' => 'ج',
                'letter_name_arabic' => 'جيم',
                'letter_name_urdu' => 'جیم',
                'letter_name_english' => 'Jeem',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'زبان کا وسط اور تالو',
                'makhraj_description_english' => 'From the middle of the tongue and the palate',
                'pronunciation_tips_urdu' => 'زبان کا درمیانی حصہ تالو سے لگائیں',
                'pronunciation_tips_english' => 'Press the middle of your tongue against the palate',
                'shape_isolated' => 'ج',
                'shape_initial' => 'جـ',
                'shape_middle' => 'ـجـ',
                'shape_final' => 'ـج',
                'display_order' => 5,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['جیم']),
                'common_mistakes_urdu' => json_encode(['انگریزی J کی طرح پڑھنا', 'زبان کا غلط حصہ استعمال کرنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like English J', 'Using wrong part of tongue']),
            ],
            [
                'letter_arabic' => 'ح',
                'letter_name_arabic' => 'حاء',
                'letter_name_urdu' => 'حے',
                'letter_name_english' => 'Haa',
                'makhraj_category' => 'Al-Halq',
                'makhraj_description_urdu' => 'حلق کا درمیانی حصہ',
                'makhraj_description_english' => 'From the middle of the throat',
                'pronunciation_tips_urdu' => 'حلق کے درمیان سے زور سے ہوا نکالیں',
                'pronunciation_tips_english' => 'Force air from the middle of your throat',
                'shape_isolated' => 'ح',
                'shape_initial' => 'حـ',
                'shape_middle' => 'ـحـ',
                'shape_final' => 'ـح',
                'display_order' => 6,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['حے']),
                'common_mistakes_urdu' => json_encode(['ہے کی طرح پڑھنا', 'حلق سے نہ نکالنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like He', 'Not from the throat']),
            ],
            [
                'letter_arabic' => 'خ',
                'letter_name_arabic' => 'خاء',
                'letter_name_urdu' => 'خے',
                'letter_name_english' => 'Khaa',
                'makhraj_category' => 'Al-Halq',
                'makhraj_description_urdu' => 'حلق کا سب سے قریب والا حصہ',
                'makhraj_description_english' => 'From the closest part of the throat to the mouth',
                'pronunciation_tips_urdu' => 'حلق کے اوپری حصے سے کھر کھر کی آواز نکالیں',
                'pronunciation_tips_english' => 'Produce a scraping sound from the top of the throat',
                'shape_isolated' => 'خ',
                'shape_initial' => 'خـ',
                'shape_middle' => 'ـخـ',
                'shape_final' => 'ـخ',
                'display_order' => 7,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['خے']),
                'common_mistakes_urdu' => json_encode(['کھے کی طرح پڑھنا', 'حلق سے نہ نکالنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like Khe', 'Not from the throat']),
            ],
            [
                'letter_arabic' => 'د',
                'letter_name_arabic' => 'دال',
                'letter_name_urdu' => 'دال',
                'letter_name_english' => 'Dal',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'زبان کی نوک اور اوپر کے دانتوں کی جڑ',
                'makhraj_description_english' => 'From the tip of the tongue and the gum line of the upper front teeth',
                'pronunciation_tips_urdu' => 'زبان کی نوک کو اوپر کے دانتوں کی جڑ سے لگائیں',
                'pronunciation_tips_english' => 'Place the tip of your tongue against the gum line of your upper front teeth',
                'shape_isolated' => 'د',
                'shape_initial' => 'د',
                'shape_middle' => 'ـد',
                'shape_final' => 'ـد',
                'display_order' => 8,
                'has_ghunnah' => false,
                'is_qalqalah' => true,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['دال']),
                'common_mistakes_urdu' => json_encode(['انگریزی D کی طرح پڑھنا', 'زبان کا غلط حصہ استعمال کرنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like English D', 'Using wrong part of tongue']),
            ],
            [
                'letter_arabic' => 'ذ',
                'letter_name_arabic' => 'ذال',
                'letter_name_urdu' => 'ذال',
                'letter_name_english' => 'Dhal',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'زبان کی نوک اور اوپر کے دانتوں کے کنارے',
                'makhraj_description_english' => 'From the tip of the tongue and the edges of the upper front teeth',
                'pronunciation_tips_urdu' => 'زبان کی نوک اوپر کے دانتوں کے درمیان رکھ کر آواز نکالیں',
                'pronunciation_tips_english' => 'Place the tip of your tongue between your upper front teeth and produce sound',
                'shape_isolated' => 'ذ',
                'shape_initial' => 'ذ',
                'shape_middle' => 'ـذ',
                'shape_final' => 'ـذ',
                'display_order' => 9,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['ذال']),
                'common_mistakes_urdu' => json_encode(['زے یا ظے پڑھنا', 'دانتوں کے درمیان زبان نہ رکھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like Z or Zha', 'Not placing tongue between teeth']),
            ],
            [
                'letter_arabic' => 'ر',
                'letter_name_arabic' => 'راء',
                'letter_name_urdu' => 'رے',
                'letter_name_english' => 'Ra',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'زبان کی نوک کا کنارہ اور اوپر کے تالو',
                'makhraj_description_english' => 'From the edge of the tip of the tongue and the palate',
                'pronunciation_tips_urdu' => 'زبان کی نوک کو تالو سے لگا کر لرزائیں',
                'pronunciation_tips_english' => 'Vibrate the tip of your tongue against the palate',
                'shape_isolated' => 'ر',
                'shape_initial' => 'ر',
                'shape_middle' => 'ـر',
                'shape_final' => 'ـر',
                'display_order' => 10,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['رے']),
                'common_mistakes_urdu' => json_encode(['انگریزی R کی طرح پڑھنا', 'زبان کو نہ لرزانا']),
                'common_mistakes_english' => json_encode(['Pronouncing like English R', 'Not vibrating the tongue']),
            ],
            [
                'letter_arabic' => 'ز',
                'letter_name_arabic' => 'زاي',
                'letter_name_urdu' => 'زے',
                'letter_name_english' => 'Zay',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'دانتوں کی جڑ اور زبان کی نوک سے',
                'makhraj_description_english' => 'From the tip of the tongue and the gum line',
                'pronunciation_tips_urdu' => 'زبان کی نوک کو دانتوں کی جڑ سے لگا کر آواز نکالیں',
                'pronunciation_tips_english' => 'Press tongue tip against gum line and produce sound',
                'shape_isolated' => 'ز',
                'shape_initial' => 'ز',
                'shape_middle' => 'ـز',
                'shape_final' => 'ـز',
                'display_order' => 11,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['زے']),
                'common_mistakes_urdu' => json_encode(['ذال کی طرح پڑھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like Dhal']),
            ],
            [
                'letter_arabic' => 'س',
                'letter_name_arabic' => 'سين',
                'letter_name_urdu' => 'سین',
                'letter_name_english' => 'Seen',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'زبان کی نوک اور نچلے دانتوں سے',
                'makhraj_description_english' => 'From the tip of the tongue and lower teeth',
                'pronunciation_tips_urdu' => 'زبان کی نوک نچلے دانتوں کے پیچھے رکھ کر ہوا نکالیں',
                'pronunciation_tips_english' => 'Place tongue tip behind lower teeth and blow air',
                'shape_isolated' => 'س',
                'shape_initial' => 'سـ',
                'shape_middle' => 'ـسـ',
                'shape_final' => 'ـس',
                'display_order' => 12,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['سین']),
                'common_mistakes_urdu' => json_encode(['ص کی طرح پڑھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like Saud']),
            ],
            [
                'letter_arabic' => 'ش',
                'letter_name_arabic' => 'شين',
                'letter_name_urdu' => 'شین',
                'letter_name_english' => 'Sheen',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'زبان کا درمیانی حصہ اور تالو',
                'makhraj_description_english' => 'From the middle of the tongue and the palate',
                'pronunciation_tips_urdu' => 'زبان کو تالو سے لگا کر ش کی آواز نکالیں',
                'pronunciation_tips_english' => 'Press tongue against palate to produce Sh sound',
                'shape_isolated' => 'ش',
                'shape_initial' => 'شـ',
                'shape_middle' => 'ـشـ',
                'shape_final' => 'ـش',
                'display_order' => 13,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['شین']),
                'common_mistakes_urdu' => json_encode(['س اور ش میں فرق نہ کرنا']),
                'common_mistakes_english' => json_encode(['Confusing Seen and Sheen']),
            ],
            [
                'letter_arabic' => 'ص',
                'letter_name_arabic' => 'صاد',
                'letter_name_urdu' => 'صاد',
                'letter_name_english' => 'Saud',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'زبان کی نوک اور دانتوں کی جڑ (مخصوص انداز)',
                'makhraj_description_english' => 'Tip of tongue and gum line (with specific mouth shape)',
                'pronunciation_tips_urdu' => 'منہ کو گول کر کے زبان کو اوپر کی طرف اٹھائیں',
                'pronunciation_tips_english' => 'Round your mouth and raise your tongue upward',
                'shape_isolated' => 'ص',
                'shape_initial' => 'صـ',
                'shape_middle' => 'ـصـ',
                'shape_final' => 'ـص',
                'display_order' => 14,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['صاد']),
                'common_mistakes_urdu' => json_encode(['س کی طرح پڑھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like Seen']),
            ],
            [
                'letter_arabic' => 'ض',
                'letter_name_arabic' => 'ضاد',
                'letter_name_urdu' => 'ضاد',
                'letter_name_english' => 'Daud',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'زبان کا کنارہ اور اوپر کے داڑھ',
                'makhraj_description_english' => 'From the side of the tongue and the upper molars',
                'pronunciation_tips_urdu' => 'زبان کا کنارہ داڑھوں سے لگائیں اور موٹی آواز نکالیں',
                'pronunciation_tips_english' => 'Press side of tongue against molars and produce heavy sound',
                'shape_isolated' => 'ض',
                'shape_initial' => 'ضـ',
                'shape_middle' => 'ـضـ',
                'shape_final' => 'ـض',
                'display_order' => 15,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['ضاد']),
                'common_mistakes_urdu' => json_encode(['ز کی طرح پڑھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like Zay']),
            ],
            [
                'letter_arabic' => 'ط',
                'letter_name_arabic' => 'طاء',
                'letter_name_urdu' => 'طوئے',
                'letter_name_english' => 'Tua',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'زبان کی نوک اور دانتوں کی جڑ (موٹی آواز)',
                'makhraj_description_english' => 'Tip of tongue and gum line (heavy sound)',
                'pronunciation_tips_urdu' => 'منہ کو گول کر کے موٹی ت کی آواز نکالیں',
                'pronunciation_tips_english' => 'Round mouth and produce heavy T sound',
                'shape_isolated' => 'ط',
                'shape_initial' => 'طـ',
                'shape_middle' => 'ـطـ',
                'shape_final' => 'ـط',
                'display_order' => 16,
                'has_ghunnah' => false,
                'is_qalqalah' => true,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['طوئے']),
                'common_mistakes_urdu' => json_encode(['ت کی طرح پڑھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like Ta']),
            ],
            [
                'letter_arabic' => 'ظ',
                'letter_name_arabic' => 'ظاء',
                'letter_name_urdu' => 'ظوئے',
                'letter_name_english' => 'Zua',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'زبان کی نوک اور دانتوں کے کنارے (موٹی آواز)',
                'makhraj_description_english' => 'Tip of tongue and teeth edges (heavy sound)',
                'pronunciation_tips_urdu' => 'منہ گول کر کے موٹی ذ کی آواز نکالیں',
                'pronunciation_tips_english' => 'Round mouth and produce heavy Dh sound',
                'shape_isolated' => 'ظ',
                'shape_initial' => 'ظـ',
                'shape_middle' => 'ـظـ',
                'shape_final' => 'ـظ',
                'display_order' => 17,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['ظوئے']),
                'common_mistakes_urdu' => json_encode(['ز یا ذ کی طرح پڑھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like Zay or Dhal']),
            ],
            [
                'letter_arabic' => 'ع',
                'letter_name_arabic' => 'عين',
                'letter_name_urdu' => 'عین',
                'letter_name_english' => 'Ain',
                'makhraj_category' => 'Al-Halq',
                'makhraj_description_urdu' => 'حلق کا درمیانی حصہ',
                'makhraj_description_english' => 'From the middle of the throat',
                'pronunciation_tips_urdu' => 'حلق کو دبا کر ع کی آواز نکالیں',
                'pronunciation_tips_english' => 'Constrict the throat to produce Ain sound',
                'shape_isolated' => 'ع',
                'shape_initial' => 'عـ',
                'shape_middle' => 'ـعـ',
                'shape_final' => 'ـع',
                'display_order' => 18,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['عین']),
                'common_mistakes_urdu' => json_encode(['الف کی طرح پڑھنا', 'آ کی طرح پڑھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like Alif', 'Pronouncing like A']),
            ],
            [
                'letter_arabic' => 'غ',
                'letter_name_arabic' => 'غين',
                'letter_name_urdu' => 'غین',
                'letter_name_english' => 'Ghain',
                'makhraj_category' => 'Al-Halq',
                'makhraj_description_urdu' => 'حلق کا اوپری حصہ',
                'makhraj_description_english' => 'From the upper part of the throat',
                'pronunciation_tips_urdu' => 'حلق کے اوپری حصے سے کھر کھر کی آواز نکالیں',
                'pronunciation_tips_english' => 'Produce a scraping sound from upper throat',
                'shape_isolated' => 'غ',
                'shape_initial' => 'غـ',
                'shape_middle' => 'ـغـ',
                'shape_final' => 'ـغ',
                'display_order' => 19,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['غین']),
                'common_mistakes_urdu' => json_encode(['خ اور غ میں فرق نہ کرنا']),
                'common_mistakes_english' => json_encode(['Confusing Khaa and Ghain']),
            ],
            [
                'letter_arabic' => 'ف',
                'letter_name_arabic' => 'فاء',
                'letter_name_urdu' => 'فے',
                'letter_name_english' => 'Fa',
                'makhraj_category' => 'Ash-Shafataan',
                'makhraj_description_urdu' => 'نچلے ہونٹ اور اوپر کے دانتوں سے',
                'makhraj_description_english' => 'From the lower lip and upper teeth',
                'pronunciation_tips_urdu' => 'نچلے ہونٹ کو اوپر کے دانتوں سے لگائیں',
                'pronunciation_tips_english' => 'Press lower lip against upper teeth',
                'shape_isolated' => 'ف',
                'shape_initial' => 'فـ',
                'shape_middle' => 'ـفـ',
                'shape_final' => 'ـف',
                'display_order' => 20,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['فے']),
                'common_mistakes_urdu' => json_encode(['پھ کی طرح پڑھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like Ph']),
            ],
            [
                'letter_arabic' => 'ق',
                'letter_name_arabic' => 'قاف',
                'letter_name_urdu' => 'قاف',
                'letter_name_english' => 'Qaf',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'زبان کی پچھلی جڑ اور تالو',
                'makhraj_description_english' => 'From the back of the tongue and the palate',
                'pronunciation_tips_urdu' => 'زبان کی جڑ کو تالو سے لگا کر کھکھ کی آواز نکالیں',
                'pronunciation_tips_english' => 'Press back of tongue against palate and produce Q sound',
                'shape_isolated' => 'ق',
                'shape_initial' => 'قـ',
                'shape_middle' => 'ـقـ',
                'shape_final' => 'ـق',
                'display_order' => 21,
                'has_ghunnah' => false,
                'is_qalqalah' => true,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['قاف']),
                'common_mistakes_urdu' => json_encode(['ک یا خ کی طرح پڑھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like K or Kh']),
            ],
            [
                'letter_arabic' => 'ك',
                'letter_name_arabic' => 'كاف',
                'letter_name_urdu' => 'کاف',
                'letter_name_english' => 'Kaf',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'زبان کی پچھلی جڑ اور تالو (ق سے ذرا نیچے)',
                'makhraj_description_english' => 'From the back of the tongue and palate (slightly lower than Qaf)',
                'pronunciation_tips_urdu' => 'زبان کی پچھلی جڑ کو تالو سے لگا کر ک کی آواز نکالیں',
                'pronunciation_tips_english' => 'Press back of tongue against palate to produce K sound',
                'shape_isolated' => 'ك',
                'shape_initial' => 'كـ',
                'shape_middle' => 'ـكـ',
                'shape_final' => 'ـك',
                'display_order' => 22,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['کاف']),
                'common_mistakes_urdu' => json_encode(['ق اور ک میں فرق نہ کرنا']),
                'common_mistakes_english' => json_encode(['Confusing Qaf and Kaf']),
            ],
            [
                'letter_arabic' => 'ل',
                'letter_name_arabic' => 'لام',
                'letter_name_urdu' => 'لام',
                'letter_name_english' => 'Lam',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'زبان کا کنارہ اور اوپر کے دانت',
                'makhraj_description_english' => 'From the side of the tongue and the upper teeth',
                'pronunciation_tips_urdu' => 'زبان کا کنارہ اوپر کے دانتوں سے لگائیں',
                'pronunciation_tips_english' => 'Press side of tongue against upper teeth',
                'shape_isolated' => 'ل',
                'shape_initial' => 'لـ',
                'shape_middle' => 'ـلـ',
                'shape_final' => 'ـل',
                'display_order' => 23,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['لام']),
                'common_mistakes_urdu' => json_encode(['انگریزی L کی طرح پڑھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like English L']),
            ],
            [
                'letter_arabic' => 'م',
                'letter_name_arabic' => 'ميم',
                'letter_name_urdu' => 'میم',
                'letter_name_english' => 'Meem',
                'makhraj_category' => 'Ash-Shafataan',
                'makhraj_description_urdu' => 'ہونٹوں کو بند کر کے',
                'makhraj_description_english' => 'By closing the lips',
                'pronunciation_tips_urdu' => 'ہونٹ بند کر کے ناک سے آواز نکالیں',
                'pronunciation_tips_english' => 'Close lips and produce sound from nose',
                'shape_isolated' => 'م',
                'shape_initial' => 'مـ',
                'shape_middle' => 'ـمـ',
                'shape_final' => 'ـم',
                'display_order' => 24,
                'has_ghunnah' => true,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['میم']),
                'common_mistakes_urdu' => json_encode(['ہونٹ نہ بند کرنا']),
                'common_mistakes_english' => json_encode(['Not closing lips properly']),
            ],
            [
                'letter_arabic' => 'ن',
                'letter_name_arabic' => 'نون',
                'letter_name_urdu' => 'نون',
                'letter_name_english' => 'Noon',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'زبان کی نوک اور اوپر کے دانتوں کی جڑ',
                'makhraj_description_english' => 'From the tip of the tongue and the gum line',
                'pronunciation_tips_urdu' => 'زبان کی نوک دانتوں کی جڑ سے لگا کر ناک سے آواز نکالیں',
                'pronunciation_tips_english' => 'Press tongue tip against gum line and produce sound from nose',
                'shape_isolated' => 'ن',
                'shape_initial' => 'نـ',
                'shape_middle' => 'ـنـ',
                'shape_final' => 'ـن',
                'display_order' => 25,
                'has_ghunnah' => true,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['نون']),
                'common_mistakes_urdu' => json_encode(['انگریزی N کی طرح پڑھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like English N']),
            ],
            [
                'letter_arabic' => 'ه',
                'letter_name_arabic' => 'هاء',
                'letter_name_urdu' => 'ہے',
                'letter_name_english' => 'Ha',
                'makhraj_category' => 'Al-Halq',
                'makhraj_description_urdu' => 'حلق کا سب سے نیچے والا حصہ',
                'makhraj_description_english' => 'From the deepest part of the throat',
                'pronunciation_tips_urdu' => 'حلق سے ہلکی ہ کی آواز نکالیں',
                'pronunciation_tips_english' => 'Produce light H sound from the throat',
                'shape_isolated' => 'ه',
                'shape_initial' => 'هـ',
                'shape_middle' => 'ـهـ',
                'shape_final' => 'ـه',
                'display_order' => 26,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => false,
                'similar_urdu_sounds' => json_encode(['ہے']),
                'common_mistakes_urdu' => json_encode(['ح اور ہ میں فرق نہ کرنا']),
                'common_mistakes_english' => json_encode(['Confusing Haa and Ha']),
            ],
            [
                'letter_arabic' => 'و',
                'letter_name_arabic' => 'واو',
                'letter_name_urdu' => 'واو',
                'letter_name_english' => 'Waw',
                'makhraj_category' => 'Ash-Shafataan',
                'makhraj_description_urdu' => 'ہونٹوں کو گول کر کے',
                'makhraj_description_english' => 'By rounding the lips',
                'pronunciation_tips_urdu' => 'ہونٹ گول کر کے و کی آواز نکالیں',
                'pronunciation_tips_english' => 'Round lips to produce W sound',
                'shape_isolated' => 'و',
                'shape_initial' => 'و',
                'shape_middle' => 'ـو',
                'shape_final' => 'ـو',
                'display_order' => 27,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => true,
                'similar_urdu_sounds' => json_encode(['واو']),
                'common_mistakes_urdu' => json_encode(['انگریزی V یا W کی طرح پڑھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like English V or W']),
            ],
            [
                'letter_arabic' => 'ي',
                'letter_name_arabic' => 'ياء',
                'letter_name_urdu' => 'یاء',
                'letter_name_english' => 'Ya',
                'makhraj_category' => 'Al-Lisan',
                'makhraj_description_urdu' => 'زبان کا درمیانی حصہ اور تالو',
                'makhraj_description_english' => 'From the middle of the tongue and the palate',
                'pronunciation_tips_urdu' => 'زبان کا درمیانی حصہ تالو سے لگا کر ی کی آواز نکالیں',
                'pronunciation_tips_english' => 'Press middle of tongue against palate to produce Y sound',
                'shape_isolated' => 'ي',
                'shape_initial' => 'يـ',
                'shape_middle' => 'ـيـ',
                'shape_final' => 'ـي',
                'display_order' => 28,
                'has_ghunnah' => false,
                'is_qalqalah' => false,
                'is_madd_letter' => true,
                'similar_urdu_sounds' => json_encode(['یاء']),
                'common_mistakes_urdu' => json_encode(['انگریزی Y کی طرح پڑھنا']),
                'common_mistakes_english' => json_encode(['Pronouncing like English Y']),
            ],
        ];

        foreach ($letters as $letter) {
            ArabicLetter::firstOrCreate(
                ['letter_arabic' => $letter['letter_arabic']],
                array_merge($letter, [
                    'uuid' => Str::uuid(), // ✅ ADD THIS LINE
                ])
            );
        }

        $this->command->info('Arabic letters seeded successfully: ' . count($letters) . ' letters.');
    }
}
